### PR TITLE
remove DBus

### PR DESCRIPTION
**Pull request by geekosaur**
I haven't tested this but it should be correct

### CODE REVIEW

**Review by Ahanaf-Ether — APPROVED** [review]

**Comment by Ahanaf-Ether** [comment]
Its for the old file though!

**Comment by geekosaur** [comment]
Yes, I actually sat on this for an hour because I wasn't expecting *two* confirmation screens from github, sorry. It looks like you've already done this and can ignore the PR.

**Comment by Ahanaf-Ether** [comment]
Thanks a lot Mate! I really appricate your help. <3

**Comment by Ahanaf-Ether** [comment]
Ok.hs is the old config!

**Comment by Ahanaf-Ether** [comment]
Turns out i already had removed dbus

**Pull request closed without merging**
